name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r auth-service/requirements.txt
          pip install -r checkout-service/requirements.txt
          pip install -r product-service/requirements.txt

      - name: Run tests
        run: |
          # Hier sollten Ihre Tests ausgeführt werden
          echo "Running tests..."

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push auth-service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest ./auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: Build and push checkout-service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/checkout-service:latest ./checkout-service
          docker push ${{ secrets.DOCKER_USERNAME }}/checkout-service:latest

      - name: Build and push product-service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest ./product-service
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.18.0

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/auth-deployment.yaml
          kubectl apply -f k8s/auth-service.yaml
          kubectl apply -f k8s/checkout-deployment.yaml
          kubectl apply -f k8s/checkout-service.yaml
          kubectl apply -f k8s/product-deployment.yaml
          kubectl apply -f k8s/product-service.yaml
          kubectl apply -f k8s/ingress.yaml
